### ISSUE TITLE
Create a priority list for French vocabulary

### ISSUE THREAD

**Issue by hugolpz** [edouard-lopez/lsf#1]
- [Lingua-Libre-Lists](https://github.com/hugolpz/Lingua-Libre-Lists)

**Comment by edouard-lopez** [comment]
Thanks, I'm not at these stage right now, I'm still gathering a little dataset so I do realistic user testing.

Please, be aware I don't aim to produce content myself, but reuse from other sources. 

For instance, I'm in the process of extracting word from 600 words from _Apprendre 300 mots du quotidien en LSF_ [part 1](https://www.youtube.com/watch?v=rz3jw0_XXoc) and [part 2](https://www.youtube.com/watch?v=DbTKAbY-i0A) which are more common used one.

In the future, I hope to be able to use data from [Signe de Sens](http://elix-lsf.fr/).
